### ISSUE TITLE
over_the_wire.txt fails

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/z3c.etestbrowser#1]
```
mg@platonas: ~/src/zopefoundation/z3c.etestbrowser [git:master=] $ bin/test -pvc1
Running tests at level 1
Running z3c.etestbrowser.BrowserLayer tests:
  Set up z3c.etestbrowser.BrowserLayer in 0.599 seconds.
  Running:

  Ran 1 tests with 0 failures, 0 errors, 0 skipped in 0.147 seconds.
Running z3c.etestbrowser.tests.ETestBrowserLayer tests:
  Tear down z3c.etestbrowser.BrowserLayer in 0.001 seconds.
  Set up z3c.etestbrowser.tests.ETestBrowserLayer in 0.382 seconds.
  Running:
    2/2 (100.0%) /home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/over_the_wire.txt

Failure in test /home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/over_the_wire.txt
Failed doctest test for over_the_wire.txt
  File "/home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/over_the_wire.txt", line 0

----------------------------------------------------------------------
File "/home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/over_the_wire.txt", line 20, in over_the_wire.txt
Failed example:
    browser.open('http://google.com/ncr')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest over_the_wire.txt[3]>", line 1, in <module>
        browser.open('http://google.com/ncr')
      File "/home/mg/.buildout/eggs/zope.testbrowser-4.0.4-py2.7.egg/zope/testbrowser/browser.py", line 264, in open
        self.mech_browser.open(url, data)
      File "/home/mg/.buildout/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py", line 203, in open
        return self._mech_open(url, data, timeout=timeout)
      File "/home/mg/.buildout/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py", line 255, in _mech_open
        raise response
    RobotExclusionError: HTTP Error 403: request disallowed by robots.txt
----------------------------------------------------------------------
File "/home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/over_the_wire.txt", line 21, in over_the_wire.txt
Failed example:
    browser.url
Differences (ndiff with -expected +actual):
    - 'http://www.google.com/'
    ?         ----
    + 'http://google.com/ncr'
    ?                    +++
----------------------------------------------------------------------
File "/home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/over_the_wire.txt", line 23, in over_the_wire.txt
Failed example:
    'html' in browser.contents.lower()
Differences (ndiff with -expected +actual):
    - True
    + False
----------------------------------------------------------------------
File "/home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/over_the_wire.txt", line 28, in over_the_wire.txt
Failed example:
    browser.etree.xpath('//body')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest over_the_wire.txt[6]>", line 1, in <module>
        browser.etree.xpath('//body')
      File "/home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/browser.py", line 78, in etree
        content_type = self.headers['content-type']
      File "/usr/lib/python2.7/rfc822.py", line 388, in __getitem__
        return self.dict[name.lower()]
    KeyError: 'content-type'
----------------------------------------------------------------------
File "/home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/over_the_wire.txt", line 33, in over_the_wire.txt
Failed example:
    browser.getControl(name='q').value = 'z3c.etestbrowser'
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest over_the_wire.txt[7]>", line 1, in <module>
        browser.getControl(name='q').value = 'z3c.etestbrowser'
      File "/home/mg/.buildout/eggs/zope.testbrowser-4.0.4-py2.7.egg/zope/testbrowser/browser.py", line 392, in getControl
        label, name, self.mech_browser.forms(), include_subcontrols=True)
      File "/home/mg/.buildout/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py", line 419, in forms
        raise BrowserStateError("not viewing HTML")
    BrowserStateError: not viewing HTML
----------------------------------------------------------------------
File "/home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/over_the_wire.txt", line 37, in over_the_wire.txt
Failed example:
    browser.getControl('Google Search').click()
Differences (ndiff with -expected +actual):
      Traceback (most recent call last):
    - ...
    - RobotExclusionError: HTTP Error 403: request disallowed by robots.txt
    +   File "/usr/lib/python2.7/doctest.py", line 1315, in __run
    +     compileflags, 1) in test.globs
    +   File "<doctest over_the_wire.txt[8]>", line 1, in <module>
    +     browser.getControl('Google Search').click()
    +   File "/home/mg/.buildout/eggs/zope.testbrowser-4.0.4-py2.7.egg/zope/testbrowser/browser.py", line 392, in getControl
    +     label, name, self.mech_browser.forms(), include_subcontrols=True)
    +   File "/home/mg/.buildout/eggs/mechanize-0.2.5-py2.7.egg/mechanize/_mechanize.py", line 419, in forms
    +     raise BrowserStateError("not viewing HTML")
    + BrowserStateError: not viewing HTML


  Ran 2 tests with 1 failures, 0 errors, 0 skipped in 0.267 seconds.
Tearing down left over layers:
  Tear down z3c.etestbrowser.tests.ETestBrowserLayer in 0.001 seconds.

Tests with failures:
   /home/mg/src/zopefoundation/z3c.etestbrowser/src/z3c/etestbrowser/over_the_wire.txt
Total: 3 tests, 1 failures, 0 errors, 0 skipped in 1.557 seconds.

[exited with 1]
```

See also https://github.com/zopefoundation/zope.testbrowser/issues/12

**Comment by icemac** [comment]
@mgedmin Is this issue still valid?
It does neither fail on my machine nor on TravisCI.

**Comment by mgedmin** [comment]
Excellent!
